apiVersion: v1
kind: Secret
metadata:
  name: report-server-github-deploy
  namespace: flux-system
type: Opaque
data:
  identity: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNDV21QUmp3NjR0U0RvRlpRUTRQMGhKOE91c2pJZkhNQjNlbUlBVjNkOWlpQUFBQUtEVG9VVVkwNkZGCkdBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQ1dtUFJqdzY0dFNEb0ZaUVE0UDBoSjhPdXNqSWZITUIzZW1JQVYzZDlpaUEKQUFBRUFiTWJZclJpSFJzenp2UllUcFQzbXVDYVNqdFd1NkdVUjJ5bzR0VXFUQnVaYVk5R1BEcmkxSU9nVmxCRGcvU0Vudwo2NnlNaDhjd0hkNllnQlhkMzJLSUFBQUFHV1pzZFhndGNtVndiM0owTFhObGNuWmxjaTFrWlhCc2Iza0JBZ01FCi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  identity.pub: c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUphWTlHUERyaTFJT2dWbEJEZy9TRW53NjZ5TWg4Y3dIZDZZZ0JYZDMyS0kgZmx1eC1yZXBvcnQtc2VydmVyLWRlcGxveQ0K
