apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: report-server
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: report-server
  policy:
    semver:
      range: ">=v0.0.0"
