apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: report-server-chart
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/beingyash/report-server.git
  ref:
    branch: main
  ignore: |
    # only track the helm chart
    /*
    !/charts/report-server/
