apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "report-server.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: report-server-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "report-server.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
